$(".wp-page-white-persons-others .click-others-sections").click(function(event) {
    $(".wp-page-white-messages-chat div").removeClass("active")
    $("#" + event.currentTarget.id + "-div").addClass("active")
    $(".wp-page-white-messages").addClass("active")
    $(".wp-web-backgorund").addClass("not-active")
    $(".left-texts").removeClass("leftyuzde40")
    $(".right-texts").removeClass("rightyuzde40")
    console.log("#" + event.currentTarget.id + "-div")
})

$(".wp-page-white-persons-others .click-others-sections").click(function(event) {
    $(".headers-class .headers").removeClass("head-active")
    $("#" + event.currentTarget.id + "header").addClass("head-active")
    console.log("#" + event.currentTarget.id + "header")
})

$(".profile-click").click(function(event) {
    $(".wp-page-white-persons").removeClass("active")
    $(".wp-page-white-persons").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")

    $(".profile-page").removeClass("not-active")
    $(".profile-page").addClass("active")
})

$(".profile-click-return").click(function(event) {
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".wp-page-white-persons").removeClass("not-active")
    $(".wp-page-white-persons").addClass("active")
})

$(".communications-click").click(function(event) {
    $(".wp-page-white-persons").removeClass("active")
    $(".wp-page-white-persons").addClass("not-active")
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")

    $(".communications-page").removeClass("not-active")
    $(".communications-page").addClass("active")
})

$(".communications-click-return").click(function(event) {
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".wp-page-white-persons").removeClass("not-active")
    $(".wp-page-white-persons").addClass("active")
})

$(".mycase-click").click(function(event) {
    $(".wp-background").removeClass("active")
    $(".wp-background").addClass("not-active")
    $(".wp-page").removeClass("active")
    $(".wp-page").addClass("not-active")
    $(".wp-page-white-persons").removeClass("active")
    $(".wp-page-white-persons").addClass("not-active")
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".mycase-page").removeClass("not-active")
    $(".mycase-page").addClass("active")
    $(".mycase-page-background").removeClass("not-active")
    $(".mycase-page-background").addClass("active")
})

$(".mycase-click-return").click(function(event) {
    $(".wp-background").removeClass("not-active")
    $(".wp-background").addClass("active")
    $(".wp-page").removeClass("not-active")
    $(".wp-page").addClass("active")
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".mycase-page-background").removeClass("active")
    $(".mycase-page-background").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".wp-page-white-persons").removeClass("not-active")
    $(".wp-page-white-persons").addClass("active")
})

$(".newchat-click").click(function(event) {
    $(".wp-page-white-persons").removeClass("active")
    $(".wp-page-white-persons").addClass("not-active")
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".newchat-page").removeClass("not-active")
    $(".newchat-page").addClass("active")
})

$(".newchat-click-return").click(function(event) {
    $(".profile-page").removeClass("active")
    $(".profile-page").addClass("not-active")
    $(".communications-page").removeClass("active")
    $(".communications-page").addClass("not-active")
    $(".mycase-page").removeClass("active")
    $(".mycase-page").addClass("not-active")
    $(".newchat-page").removeClass("active")
    $(".newchat-page").addClass("not-active")
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    
    $(".wp-page-white-persons").removeClass("not-active")
    $(".wp-page-white-persons").addClass("active")
})

$(".specifications-click").click(function(event) {
    $(".specifications-page").removeClass("not-active")
    $(".specifications-page").addClass("active")
    $(".wp-page-white-persons-admin-specifications").removeClass("active")
    $(".wp-page-white-persons-admin-specifications").addClass("not-active")
    $(".wp-page-white-persons-admin-specifications-return").removeClass("not-active")
    $(".wp-page-white-persons-admin-specifications-return").addClass("active")
})

$(".specifications-click-return").click(function(event) {
    $(".specifications-page").removeClass("active")
    $(".specifications-page").addClass("not-active")
    $(".wp-page-white-persons-admin-specifications").removeClass("not-active")
    $(".wp-page-white-persons-admin-specifications").addClass("active")
    $(".wp-page-white-persons-admin-specifications-return").removeClass("active")
    $(".wp-page-white-persons-admin-specifications-return").addClass("not-active")
})

$(".messages-click").click(function(event) {
    $(".messages-page").removeClass("not-active")
    $(".messages-page").addClass("active")
    $(".message-page-first-dat").removeClass("active")
    $(".message-page-first-dat").addClass("not-active")
    $(".message-page-second-dat").removeClass("not-active")
    $(".message-page-second-dat").addClass("active")
})

$(".messages-click-return").click(function(event) {
    $(".messages-page").removeClass("active")
    $(".messages-page").addClass("not-active")
    $(".message-page-first-dat").removeClass("not-active")
    $(".message-page-first-dat").addClass("active")
    $(".message-page-second-dat").removeClass("active")
    $(".message-page-second-dat").addClass("not-active")
})

$(".wp-page-white-messages-header-a").click(function(event) {
    $(".mycase-page-div2").addClass("yuzde40")
    $(".wp-web-backgorund").addClass("yuzde40")
    $(".wp-web-backgorund-div").addClass("yuzde40")
    $(".wp-page-white-messages").addClass("yuzde40")
    $(".messages-page").addClass("yuzde40")
    $(".left-texts").addClass("leftyuzde40")
    $(".right-texts").addClass("rightyuzde40")
    $(".wp-page-white-persons-info-right").addClass("active")
    $(".wp-page-white-persons-info-right").removeClass("not-active")
})

$(".right-return-image-a").click(function(event) {
    $(".mycase-page-div2").removeClass("yuzde40")
    $(".wp-web-backgorund").removeClass("yuzde40")
    $(".wp-web-backgorund-div").removeClass("yuzde40")
    $(".wp-page-white-messages").removeClass("yuzde40")
    $(".messages-page").removeClass("yuzde40")
    $(".left-texts").removeClass("leftyuzde40")
    $(".right-texts").removeClass("rightyuzde40")
    $(".wp-page-white-persons-info-right").addClass("not-active")
    $(".wp-page-white-persons-info-right").removeClass("active")
})

$(".wp-page-white-messages-input-atac-a1").click(function(event) {
    $(".atac-ustu-simgeler").addClass("active")
    $(".atac-ustu-simgeler").removeClass("not-active")
    $(".wp-page-white-messages-input-atac-a1").addClass("not-active")
    $(".wp-page-white-messages-input-atac-a1").removeClass("active")
    $(".wp-page-white-messages-input-atac-a2").addClass("active")
    $(".wp-page-white-messages-input-atac-a2").removeClass("not-active")
})

$(".wp-page-white-messages-input-atac-a2").click(function(event) {
    $(".atac-ustu-simgeler").addClass("not-active")
    $(".atac-ustu-simgeler").removeClass("active")
    $(".wp-page-white-messages-input-atac-a1").addClass("active")
    $(".wp-page-white-messages-input-atac-a1").removeClass("not-active")
    $(".wp-page-white-messages-input-atac-a2").addClass("not-active")
    $(".wp-page-white-messages-input-atac-a2").removeClass("active")
})

$(".message-page-zero-dat").click(function(event) {
    $(".mycase-page-div2").addClass("yuzde40")
    $(".wp-web-backgorund").addClass("yuzde40")
    $(".wp-web-backgorund-div").addClass("yuzde40")
    $(".wp-page-white-messages").addClass("yuzde40")
    $(".messages-page").addClass("yuzde40")
    $(".left-texts").addClass("leftyuzde40")
    $(".right-texts").addClass("rightyuzde40")
    $(".wp-page-white-persons-info-right").addClass("active")
    $(".wp-page-white-persons-info-right").removeClass("not-active")
})